# Generated by Django 3.1.7 on 2021-03-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic_category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
