# Generated by Django 3.1.7 on 2021-03-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210318_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic_category',
            field=models.CharField(default='uncategorized', max_length=200),
        ),
    ]
